version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 log=/var/log/xdebug.log start_with_request=yes
    volumes:
      - ./src/:/var/www/html
      - ./logs:/var/log # AÑADIDA PARA LOS LOGS
networks:
  internal:
    driver: bridge